In [1]:
arr =[1,2,3,4,5]
print(arr*5)
arr=[x*5 for x in arr]
print(arr)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[5, 10, 15, 20, 25]


## NDArray

In [3]:
import numpy as np
#1d array
arr=np.array([1,2,3,4,5])


print(type(arr))
print(arr.ndim)

#2d array

arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

print(arr2*5)
print(type(arr2))
print(arr2.ndim)



arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2     
])
print(arr3*5)
print(type(arr3))
print(arr3.ndim)

<class 'numpy.ndarray'>
1
[[ 5 10 15]
 [20 25 30]]
<class 'numpy.ndarray'>
2
[[[ 5 10 15]
  [20 25 30]]

 [[ 5 10 15]
  [20 25 30]]

 [[ 5 10 15]
  [20 25 30]]]
<class 'numpy.ndarray'>
3


In [4]:
arr_mod=arr[1:4].copy()
arr_mod[0]=100
arr[1]=2
arr_mod[2]=200
print(arr_mod)
print(arr)

[100   3 200]
[1 2 3 4 5]


## Array attributes

In [5]:
#Dimension
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)
print("\n")
#shape
print(f"Array 1 data Shape:{arr.shape}")
print(f"Array 2 data Shape:{arr2.shape}")
print(f"Array 3 data Shape:{arr3.shape}")
print("\n")
#data type
print(f"Array 1 data Type:",arr.dtype)
print(f"Array 2 data Type:",arr2.dtype)
print(f"Array 3 data Type:",arr3.dtype)

print("\n")
#size
print(f"Array 1 data size:{arr.size}")
print(f"Array 2 data size:{arr2.size}")
print(f"Array 3 data size:{arr3.size}")


1
2
3


Array 1 data Shape:(5,)
Array 2 data Shape:(2, 3)
Array 3 data Shape:(3, 2, 3)


Array 1 data Type: int64
Array 2 data Type: int64
Array 3 data Type: int64


Array 1 data size:5
Array 2 data size:6
Array 3 data size:18


## Ndarray data type

In [6]:
arr = np.array([1,2,3]) 

print(arr.dtype)

arr = np.array([1.5,2.4,3.2]) 
print(arr.dtype)

int64
float64


In [7]:
arr = np.array([1,2,3.2]) 
# upcasted to float 
print(arr.dtype) 

#upcasted to string
arr = np.array([1,2,3.2,'hello']) 
print(arr.dtype) 


arr = np.array([1,True,3.25,'hello',]) 
print(arr.dtype) 

float64
<U32
<U32


## Selecting a data type for an array

In [8]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)




arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64) 

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

## Ndarray creation from existing data

In [9]:
#list 

lst = [10,20,30,40 , 40.5] 

arr = np.array(lst, dtype=np.int32) 

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst) 

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix) 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [10]:
#tuple 

tpl = (10,20,30) 

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 


int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


## Creating Ndarray from scratch

In [11]:
arr = np.ones((2,3),dtype=np.int8)
# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim) 
# print(arr.size) 

arr= np.ones_like(arr3)
print(arr)
print(arr.shape) 
print(arr.dtype) 

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)
int64


In [12]:
arr = np.empty((2,3),10)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 
print(arr.size) 

TypeError: Cannot interpret '10' as a data type

In [ ]:
# dictionary 

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [ ]:
arr = np.array(list(keys))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [ ]:
#items to ndarray
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


In [ ]:
#np.full 

arr = np.full((4,3),np.inf)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64) 

print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


## array creation with random values

In [ ]:
# np.random.rand(shape) 

arr = np.random.rand(2,3) # 0 ->1 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.45086651 0.90804983 0.23920562]
 [0.43186444 0.45871515 0.77163629]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [ ]:
# np.random.randint(start,end, shape) 

arr = np.random.randint(1,10 , (2,3))  

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)



[[4 2 5]
 [3 2 2]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [ ]:
# np.random.uniform(start,end, shape) 

arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[[50.17360839 69.08920204 94.12857163 92.69554201]
  [89.48513744 76.40739186 96.38065064 99.21787931]
  [59.12056366 94.26918163 87.74601669 72.29605353]]

 [[64.65135654 51.21721077 87.83100124 87.91534456]
  [82.88793813 50.60294822 94.68746405 95.79473981]
  [72.8973377  59.17316545 73.60282022 58.73443839]]

 [[84.81417764 64.95807961 60.05812869 72.21553812]
  [93.43008933 65.89667398 88.28346441 93.64360448]
  [84.69640201 97.43711316 51.31846444 57.3806404 ]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


In [ ]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 

print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)



[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [5]:
arr_i = np.linspace(0, 10 ,5)


print(arr_i) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[ 0.   2.5  5.   7.5 10. ]
<class 'numpy.ndarray'>
int64
(5,)
1
5


In [9]:
arr = np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)

[1 0 0 0 5]


In [ ]:
print(arr)

arr2[0][2]=100
print(arr2)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
[[  1   2 100]
 [  4   5   6]]


In [ ]:
#slicing 
#1d = arr[start:end:step] 

arr_mod = arr[1:4]
arr[1] = 2


arr_mod[2] = 200
print(arr_mod)
print(arr)

[  2.           3.03143313 200.        ]
[  1.           2.           3.03143313 200.           9.18958684
  16.        ]


In [ ]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]
# print(arr2)

#getting a row

row_0 = arr2[0:1,]

row_1=arr2[1:,]
col_0 =arr2[:: ,1:2]

portion= arr3[0:2, 0:2]
print(portion)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Advance indexing

In [ ]:
lst= np.array([10,20,30,40,50])

values= lst[[0,3,1]]
print(values)

[10 40 20]


In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


AttributeError: 'list' object has no attribute 'ndim'