In [2]:
import numpy as np

arr = np.random.randint(1,100, size = (10,5))
print(arr)

[[44 37 75 73 11]
 [48 20 37 74 10]
 [95 89 72  2  9]
 [88 86  1 75 77]
 [ 7 89  1 93 74]
 [64  5  9 55 64]
 [76 64 23 72 33]
 [ 9 80 46 71 29]
 [91 87 14 60  3]
 [73 90 33 20 88]]


In [18]:
b= arr.reshape(5,10)

In [19]:
b.shape
b.ndim
b

array([[59, 53, 30,  7, 83, 71, 96,  7, 96, 59],
       [51, 68, 59, 68, 77, 65, 60, 91, 69, 46],
       [17,  6, 51, 54, 80,  1, 22,  5, 41, 38],
       [94, 21, 14, 22, 39, 74, 50, 75, 75, 51],
       [25, 29,  5, 57, 81, 43, 56, 20, 63, 13]])

In [23]:

flatten = b.flatten()
print(flatten)

column_wise_flattening = np.ravel(b,order ="C")
print(column_wise_flattening)

[59 53 30  7 83 71 96  7 96 59 51 68 59 68 77 65 60 91 69 46 17  6 51 54
 80  1 22  5 41 38 94 21 14 22 39 74 50 75 75 51 25 29  5 57 81 43 56 20
 63 13]
[59 53 30  7 83 71 96  7 96 59 51 68 59 68 77 65 60 91 69 46 17  6 51 54
 80  1 22  5 41 38 94 21 14 22 39 74 50 75 75 51 25 29  5 57 81 43 56 20
 63 13]


In [28]:
a = np.random.randint(1,100, size=(2,3))
b = np.random.randint(20,100, size=(2,3))

print(a)
print("\n")
print(b)

[[92 18 48]
 [37 15 91]]


[[35 58 99]
 [66 24 47]]


### Concatenate

In [32]:
con_row = np.concatenate((a,b), axis=0) #row wise
print(con_row)
con_col = np.concatenate((a,b), axis=1) #col wise  
print("\n")
print(con_col)

[[92 18 48]
 [37 15 91]
 [35 58 99]
 [66 24 47]]


[[92 18 48 35 58 99]
 [37 15 91 66 24 47]]


### Transpose

In [35]:
mat = np.array([[10,20,30],[30,40,50]])

tarnspose = mat.T #row to col

print(tarnspose)


[[10 30]
 [20 40]
 [30 50]]


In [3]:

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ]) 

add = np.add(x,y) 
print(add)

sub = x-y 
print(sub)

mul = x*y 
print(mul) 


div = x/y 
print(div) 

remainder = x % y

print(remainder) 


[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [4]:
# mathematical function 

# trigonometry 

# sin , cos , tan takes values in radian 

sin_val = np.sin(x)
print(sin_val) 

cos_val = np.cos(x)
print(cos_val) 

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad 

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [5]:
x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


base_2_log_value = np.log2(x) 
print(base_2_log_value)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [6]:
# different 
s = np.sum(x)
print(s)

#prefix sum 
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


In [7]:
#inplace 
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z) 

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [8]:
# copy sorting
print(x)
sort_arr = np.sort(x) 

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [10]:
# 2d array sorting 
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1 

hor_sort = np.sort(mat,axis=1)
print(hor_sort)
print("\n")
vert_sort = np.sort(mat,axis=0)
print(vert_sort)


[[ 3  5 10]
 [ 4  8  9]]


[[ 8  3  5]
 [10  4  9]]


## Searching

In [11]:
print(x)

[ 10   8  16 100]


In [23]:
index = np.where(x==8)
print(index)
index = np.where(x>8,x,5)
print(index)

(array([1]),)
[ 10   5  16 100]


In [24]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [31]:
index=np.where(mat>5)
print(index)
arrt=np.where(mat>5,mat,0)
print(arrt)

(array([0, 1, 1]), array([0, 0, 2]))
[[10  0  0]
 [ 8  0  9]]


In [33]:
a= np.random.randint(1,100, size = (100,))

print(a)

[88 76  3 72  6 81 21 59 17 51 13 91 29 18 41 57 79 94 51 47 95 64 80 11
 57 10 14 74 43 45 12 55 65 43 52 62 79 86  7 37 17 92 70 53 99  4 64 29
 64 26 73 63 93 33 55 25 56 62 74 54  6 44 85 46 51 70 79 53 47 69 56 58
 93 26 99 62 35 15 29 93 37 45 39 37  1  5 36 39 31 45 72 16 97 95 60 69
 57 52 77 63]


In [43]:
value_greater_tan_60= np.count_nonzero(a=97)
print(value_greater_tan_60)

1


In [47]:
unique_value= np.unique(a,return_counts=True)
print(unique_value)

(array([ 1,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 25,
       26, 29, 31, 33, 35, 36, 37, 39, 41, 43, 44, 45, 46, 47, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 62, 63, 64, 65, 69, 70, 72, 73, 74, 76,
       77, 79, 80, 81, 85, 86, 88, 91, 92, 93, 94, 95, 97, 99]), array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 3, 1, 1, 1,
       1, 3, 2, 1, 2, 1, 3, 1, 2, 3, 2, 2, 1, 2, 2, 3, 1, 1, 1, 3, 2, 3,
       1, 2, 2, 2, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 2]))


## statistical function

In [59]:
import pandas as pd

In [60]:
# data load
# data = np.genfromtxt('student.csv', delimeter=',')
df = pd.read_csv("student.csv")

df.head(4)

Math  Science  English
0    78       85       82
1    56       67       72
2    89       92       88
3    45       52       58

In [64]:
data = np.genfromtxt("student.csv", delimiter=",", skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [69]:


math_marks=data[:2,::]
print(math_marks)

[[78. 85. 82.]
 [56. 67. 72.]]
