In [ ]:
import torch

# Original X for context
X = torch.tensor([[1.0, 2.0]]) # Shape (1, 2)

# Hypothetical scenario: W is defined with an incompatible shape, e.g., (1, 2)
W_incompatible = torch.tensor([[0.5, 0.3]]) # Shape (1, 2)

print(f"X shape: {X.shape}")
print(f"Incompatible W shape: {W_incompatible.shape}")

# If we tried torch.matmul(X, W_incompatible), it would fail because X's last dimension (2)
# does not match W_incompatible's first dimension (1).
# (1, 2) @ (1, 2) -> Fails

# To make them compatible for (X @ W), W's first dimension needs to be 2.
# Since W_incompatible has 2 elements, we can reshape it to (2, 1).

# Option 1: Using .T (transpose)
W_reshaped_T = W_incompatible.T # Changes shape from (1, 2) to (2, 1)
print(f"Reshaped W using .T shape: {W_reshaped_T.shape}")

# Now, torch.matmul(X, W_reshaped_T) would work:
# (1, 2) @ (2, 1) -> (1, 1)
result_T = torch.matmul(X, W_reshaped_T)
print(f"Result with transposed W: {result_T}")

# Option 2: Using .reshape()
W_reshaped_manual = W_incompatible.reshape(2, 1) # Changes shape from (1, 2) to (2, 1)
print(f"Reshaped W using .reshape(2,1) shape: {W_reshaped_manual.shape}")

# Again, torch.matmul(X, W_reshaped_manual) would work:
result_manual = torch.matmul(X, W_reshaped_manual)
print(f"Result with manually reshaped W: {result_manual}")


X shape: torch.Size([1, 2])
Incompatible W shape: torch.Size([1, 2])
Reshaped W using .T shape: torch.Size([2, 1])
Result with transposed W: tensor([[1.1000]])
Reshaped W using .reshape(2,1) shape: torch.Size([2, 1])
Result with manually reshaped W: tensor([[1.1000]])


In [ ]:
X= torch.tensor([[1.0,2.0]])
W = torch.tensor([[0.5],
                  [0.3]])
b = torch.tensor([[0.1]])

In [ ]:
X.shape

torch.Size([1, 2])

In [ ]:
W.shape

torch.Size([2, 1])

In [ ]:
b.shape

torch.Size([1, 1])

WHY??:
Matrix multiplication requires the last dimension of the first tensor (X: size 2) to match the second-to-last dimension of the second tensor (W: size 2).  Since both are 2, the operation is valid.

In [ ]:
torch.matmul(X,W)

tensor([[1.1000]])

In [ ]:
# First layer: Z = X @ W + b
Z1 = torch.matmul(X, W) + b
print(f"Output of the first layer (Z1): {Z1}")

# Apply an activation function (e.g., ReLU) to Z1 to get A1
A1 = torch.relu(Z1)
print(f"Activated output of the first layer (A1): {A1}")

Output of the first layer (Z1): tensor([[1.2000]])
Activated output of the first layer (A1): tensor([[1.2000]])


### Mathematical Formulas for the Two-Layer Network

**a) Formula for $Z_1$:**
$Z_1 = W_1 X + b_1$

**b) ReLU Activation for $A_1$:**
$A_1 = \max(0, Z_1)$

**c) Formula for final output $\hat{y}$:**
$\hat{y} = W_2^T A_1 + b_2$  
*(Note: Since $W_2$ is $(2 \times 1)$ and $A_1$ is $(2 \times 1)$, we use the transpose of $W_2$ to get a $(1 \times 2) \cdot (2 \times 1)$ multiplication resulting in a $(1 \times 1)$ scalar).*

In [ ]:
import torch

# d) Initialization
X = torch.tensor([[1.0], [2.0]])  # (2 x 1)
W1 = torch.full((2, 2), 0.1)
b1 = torch.zeros((2, 1))
W2 = torch.full((2, 1), 0.1)
b2 = torch.zeros((1, 1))

# Layer 1
Z1 = torch.matmul(W1, X) + b1
A1 = torch.relu(Z1)

# Layer 2 (Final Output)
# Using W2.T (1x2) @ A1 (2x1) to get (1x1)
y_hat = torch.matmul(W2.T, A1) + b2

print(f"Input X:\n{X}")
print(f"Z1 (W1*X + b1):\n{Z1}")
print(f"A1 (ReLU(Z1)):\n{A1}")
print(f"Final Output y_hat:\n{y_hat}")

Input X:
tensor([[1.],
        [2.]])
Z1 (W1*X + b1):
tensor([[0.3000],
        [0.3000]])
A1 (ReLU(Z1)):
tensor([[0.3000],
        [0.3000]])
Final Output y_hat:
tensor([[0.0600]])
