In [ ]:
import torch
import torch.nn as nn

In [ ]:
#version 1
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
#version 2
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    #layer 1
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()

    #layer 2

    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    #layer 1
    out = self.linear1(features)
    out = self.relu(out)

    #layer 2
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU(), #index 1
        nn.Linear(3,1), #index 2
        nn.Sigmoid() # index 3
    )
  def forward(self,features):
    out = self.network(features)

    return out

In [ ]:
#create dataset

features = torch.rand(10,5)

In [ ]:
features

tensor([[0.8512, 0.4744, 0.8049, 0.2270, 0.9934],
        [0.5228, 0.1320, 0.5614, 0.0443, 0.2581],
        [0.8135, 0.1242, 0.8094, 0.1705, 0.3563],
        [0.5512, 0.4573, 0.5130, 0.8487, 0.6925],
        [0.0958, 0.3438, 0.4566, 0.4469, 0.6220],
        [0.2297, 0.0182, 0.3735, 0.8953, 0.8431],
        [0.1047, 0.3966, 0.3244, 0.7555, 0.7325],
        [0.4584, 0.1149, 0.3214, 0.4082, 0.7656],
        [0.3650, 0.2173, 0.0583, 0.5296, 0.6573],
        [0.1973, 0.6252, 0.7628, 0.0886, 0.9806]])

In [ ]:
features.shape[1]

5

In [ ]:
model  = Model(features.shape[1])

In [ ]:
model(features)

tensor([[0.5839],
        [0.5839],
        [0.5870],
        [0.5839],
        [0.5839],
        [0.5839],
        [0.5839],
        [0.5856],
        [0.5880],
        [0.5839]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.network[0].weight

Parameter containing:
tensor([[-0.4419,  0.1620, -0.1474, -0.3920, -0.2928],
        [-0.1022, -0.1761, -0.0104,  0.0979, -0.0596],
        [ 0.2077,  0.3673,  0.2335, -0.1282, -0.4011]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00