In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name{torch.cuda.get_device_name(0)}")

else:
  print("GPU is not available")

GPU is available
Device nameTesla T4


**Creating tensor**

In [ ]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.6042, 0.1357, 0.1052],
        [0.2078, 0.8965, 0.8989]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
import numpy as np

np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:

torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[        0, 394240208,         0],
        [        0,         0,         0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:

torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [ ]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [ ]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
x= x*100

In [ ]:
x//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [ ]:
x**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [ ]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
a = torch.rand(2,3)
b =  torch.rand(2,3)



In [ ]:
a

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [ ]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [ ]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [ ]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [ ]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [ ]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [ ]:
c = torch.tensor([-1,-2,-3,-4,-5])


In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [ ]:
torch.neg(b)

tensor([[-0.2239, -0.3023, -0.1784],
        [-0.8238, -0.5557, -0.9770]])

In [ ]:
c = torch.tensor([1.2,2.6,3.5,4.7,5.2])


In [ ]:
torch.round(c)

tensor([1., 3., 4., 5., 5.])

In [ ]:
torch.ceil(c)

tensor([2., 3., 4., 5., 6.])

In [ ]:
d = torch.tensor([100,200,300,400,500])


In [ ]:
torch.clamp(d,min=100,max=300)

tensor([100, 200, 300, 300, 300])

Reduction Oepration


In [ ]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.int32)
e

tensor([[0, 1, 9],
        [9, 8, 0]], dtype=torch.int32)

In [ ]:
torch.sum(e)


tensor(27)

In [ ]:
torch.sum(e,dim=0)

tensor([9, 9, 9])

In [ ]:
torch.sum(e,dim=1)

tensor([10, 17])

In [ ]:
torch.median(e,dim=0)

torch.return_types.median(
values=tensor([0, 1, 0], dtype=torch.int32),
indices=tensor([0, 0, 1]))

In [ ]:
torch.max(
    e
)

tensor(9, dtype=torch.int32)

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

In [ ]:
f

tensor([[7, 0, 0],
        [9, 5, 7]])

In [ ]:
g

tensor([[3, 9],
        [4, 0],
        [5, 7]])

In [ ]:
torch.matmul(f,g)

tensor([[ 21,  63],
        [ 82, 130]])

In [ ]:
#dot product

vector1 = torch.tensor([1,2])
vector2 = torch.tensor ([3,4])


In [ ]:
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
f.shape

torch.Size([2, 3])

In [ ]:
torch.transpose(f,0,1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [ ]:
k= torch.tensor([.001,20.30,40])
k

tensor([1.0000e-03, 2.0300e+01, 4.0000e+01])

In [ ]:
torch.log(k)

tensor([-6.9078,  3.0106,  3.6889])

In [ ]:
torch.exp(k)

tensor([1.0010e+00, 6.5490e+08, 2.3539e+17])

In [ ]:
torch.sqrt(k)

tensor([0.0316, 4.5056, 6.3246])

In [ ]:
torch.sigmoid(k)

tensor([0.5002, 1.0000, 1.0000])

In [ ]:
torch.relu(k)

tensor([1.0000e-03, 2.0300e+01, 4.0000e+01])

Inpace Operations


In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a +   5
b

tensor([6, 7, 8])